//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkAble2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkAble2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of MarkAble (version &lt;versionnum&gt;) is available.  Go to the web site to download it now?.
        /// </summary>
        internal static string A_new_version_of_MarkAble_is_available {
            get {
                return ResourceManager.GetString("A_new_version_of_MarkAble_is_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to existing?.
        /// </summary>
        internal static string Add_to_existing_batch_query {
            get {
                return ResourceManager.GetString("Add_to_existing_batch_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files are &lt;fileformat&gt;.
        /// </summary>
        internal static string All_files_are_fileformat {
            get {
                return ResourceManager.GetString("All_files_are_fileformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files to be processed appear to be &lt;fileformat&gt; files..
        /// </summary>
        internal static string All_files_to_be_processed_appear_to_be_fileformat_files {
            get {
                return ResourceManager.GetString("All_files_to_be_processed_appear_to_be_fileformat_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files have now been converted to bookmarking format and placed into iTunes. Look for the files in your &apos;Music&apos; folder, genre &apos;Audiobook&apos;..
        /// </summary>
        internal static string All_MP3_files_have_now_been_converted_to_bookmarking_format {
            get {
                return ResourceManager.GetString("All_MP3_files_have_now_been_converted_to_bookmarking_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the files you have selected are protected by Digital Rights Management (DRM)..
        /// </summary>
        internal static string All_of_the_files_you_have_selected_are_protected_by_Digital_Rights_Management {
            get {
                return ResourceManager.GetString("All_of_the_files_you_have_selected_are_protected_by_Digital_Rights_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this project permanently from the batch file?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_remove_this_project_permanently_from_the_batch_file {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_remove_this_project_permanently_from_the_batch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiobooks on the iPod can have chapter stops to make navigation easier.  Choose from the options below:.
        /// </summary>
        internal static string Audiobooks_on_the_iPod_can_have_chapter_stops {
            get {
                return ResourceManager.GetString("Audiobooks_on_the_iPod_can_have_chapter_stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad file type in list! : expecting MP3, got &lt;filetype&gt;..
        /// </summary>
        internal static string Bad_file_type_in_list {
            get {
                return ResourceManager.GetString("Bad_file_type_in_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_and_whip {
            get {
                object obj = ResourceManager.GetObject("book_and_whip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.  However, you can resume ripping this book at a later time, if you wish..
        /// </summary>
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CDs {
            get {
                object obj = ResourceManager.GetObject("CDs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CDs_smaller {
            get {
                object obj = ResourceManager.GetObject("CDs_smaller", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change now?.
        /// </summary>
        internal static string Change_now_query {
            get {
                return ResourceManager.GetString("Change_now_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your options to &lt;filetype&gt;?.
        /// </summary>
        internal static string Change_your_options_to_filetype {
            get {
                return ResourceManager.GetString("Change_your_options_to_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a short sound file.
        /// </summary>
        internal static string Choose_a_short_sound_file {
            get {
                return ResourceManager.GetString("Choose_a_short_sound_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting &apos;&lt;booktitle&gt;&apos; by &lt;author&gt;.
        /// </summary>
        internal static string Converting_booktitle_by_author {
            get {
                return ResourceManager.GetString("Converting_booktitle_by_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting this track seems to be taking a very long time..
        /// </summary>
        internal static string Converting_this_track_seems_to_be_taking_a_very_long_time {
            get {
                return ResourceManager.GetString("Converting_this_track_seems_to_be_taking_a_very_long_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find some of the files in project &lt;booktitle&gt;..
        /// </summary>
        internal static string Could_not_find_some_of_the_files_in_project_booktitle {
            get {
                return ResourceManager.GetString("Could_not_find_some_of_the_files_in_project_booktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical!.
        /// </summary>
        internal static string Critical_exclaim {
            get {
                return ResourceManager.GetString("Critical_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the &apos;&lt;booktitle&gt;&apos; project?.
        /// </summary>
        internal static string Delete_the_booktitle_project {
            get {
                return ResourceManager.GetString("Delete_the_booktitle_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Encoder.
        /// </summary>
        internal static string Different_Encoder {
            get {
                return ResourceManager.GetString("Different_Encoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard project?.
        /// </summary>
        internal static string Discard_project_query {
            get {
                return ResourceManager.GetString("Discard_project_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc &lt;discnum&gt; of &lt;totdiscs&gt;.
        /// </summary>
        internal static string discnum__of__totdiscs {
            get {
                return ResourceManager.GetString("discnum__of__totdiscs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want MarkAble to change the iTunes encoder rate now?.
        /// </summary>
        internal static string Do_you_want_MarkAble_to_change_the_iTunes_encoder_rate_now_query {
            get {
                return ResourceManager.GetString("Do_you_want_MarkAble_to_change_the_iTunes_encoder_rate_now_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string Do_you_want_to_continue_query {
            get {
                return ResourceManager.GetString("Do_you_want_to_continue_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to resume?.
        /// </summary>
        internal static string Do_you_want_to_resume_query {
            get {
                return ResourceManager.GetString("Do_you_want_to_resume_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        internal static string Done_exclaim {
            get {
                return ResourceManager.GetString("Done_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to each.
        /// </summary>
        internal static string Each {
            get {
                return ResourceManager.GetString("Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each file will be approx. &lt;totsize&gt;MB in size..
        /// </summary>
        internal static string Each_file_will_be_approx_totsize_MB_in_size {
            get {
                return ResourceManager.GetString("Each_file_will_be_approx_totsize_MB_in_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each file will be approx. &lt;totsize&gt;MB in size, duration &lt;duration&gt; hours..
        /// </summary>
        internal static string Each_file_will_be_approx_totsize_MB_in_size_duration_duration {
            get {
                return ResourceManager.GetString("Each_file_will_be_approx_totsize_MB_in_size_duration_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each file will have duration &lt;duration&gt; hours..
        /// </summary>
        internal static string Each_file_will_have_duration_duration_hours {
            get {
                return ResourceManager.GetString("Each_file_will_have_duration_duration_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eg: .
        /// </summary>
        internal static string Eg_colon {
            get {
                return ResourceManager.GetString("Eg_colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty!.
        /// </summary>
        internal static string Empty_exclaim {
            get {
                return ResourceManager.GetString("Empty_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file &lt;filename&gt;.
        /// </summary>
        internal static string Error_adding_file_filename {
            get {
                return ResourceManager.GetString("Error_adding_file_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error copying file &lt;filename&gt;..
        /// </summary>
        internal static string Error_copying_file_filename {
            get {
                return ResourceManager.GetString("Error_copying_file_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error_exclaim {
            get {
                return ResourceManager.GetString("Error_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on opening files.
        /// </summary>
        internal static string Error_on_opening_files {
            get {
                return ResourceManager.GetString("Error_on_opening_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file &lt;filename&gt;.
        /// </summary>
        internal static string Error_reading_file_filename {
            get {
                return ResourceManager.GetString("Error_reading_file_filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your evaluation period has now expired..
        /// </summary>
        internal static string Evaluation_expired {
            get {
                return ResourceManager.GetString("Evaluation_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have &lt;days&gt; days remaining.
        /// </summary>
        internal static string Evaluation_remaining {
            get {
                return ResourceManager.GetString("Evaluation_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every.
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer file.
        /// </summary>
        internal static string Failed_to_transfer_file {
            get {
                return ResourceManager.GetString("Failed_to_transfer_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &lt;filenum&gt; of &lt;totfiles&gt;.
        /// </summary>
        internal static string File_filenum_of_totfiles {
            get {
                return ResourceManager.GetString("File_filenum_of_totfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be &lt;totsize&gt;MB in size, duration &lt;duration&gt; hours..
        /// </summary>
        internal static string File_will_be_totsize_MB_in_size_duration_hours {
            get {
                return ResourceManager.GetString("File_will_be_totsize_MB_in_size_duration_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will have duration &lt;duration&gt; hours..
        /// </summary>
        internal static string File_will_have_duration_duration_hours_ {
            get {
                return ResourceManager.GetString("File_will_have_duration_duration_hours_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files so far ripped were encoded as &lt;filetype&gt;..
        /// </summary>
        internal static string Files_so_far_ripped_were_encoded_as_filetype {
            get {
                return ResourceManager.GetString("Files_so_far_ripped_were_encoded_as_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be larger than recommended size and/or duration unless you increase the number of parts..
        /// </summary>
        internal static string Files_will_be_larger_than_recommended_size_and_or_duration {
            get {
                return ResourceManager.GetString("Files_will_be_larger_than_recommended_size_and_or_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be too big to play at the current sampling rate unless you increase the number of parts or you are encoding at a lower rate..
        /// </summary>
        internal static string Files_will_be_too_big_to_play_at_the_current_sampling_rate {
            get {
                return ResourceManager.GetString("Files_will_be_too_big_to_play_at_the_current_sampling_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folders_small {
            get {
                object obj = ResourceManager.GetObject("folders_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, processing continued and the merged file may be OK..
        /// </summary>
        internal static string However_processing_continued_and_the_merged_file_may_be_OK {
            get {
                return ResourceManager.GetString("However_processing_continued_and_the_merged_file_may_be_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, you can resume converting this book at a later time, if you wish..
        /// </summary>
        internal static string However_you_can_resume_converting_this_book_at_a_later_time_if_you_wish {
            get {
                return ResourceManager.GetString("However_you_can_resume_converting_this_book_at_a_later_time_if_you_wish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If all of these files have been encoded the same way, you can skip the conversion process and go straight to merge..
        /// </summary>
        internal static string If_all_of_these_files_have_been_encoded_the_same_way__you_can_skip_the_conversion_process {
            get {
                return ResourceManager.GetString("If_all_of_these_files_have_been_encoded_the_same_way__you_can_skip_the_conversion" +
                        "_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If so, and if iTunes is running, quit iTunes and when it has fully closed down, click on &apos;Yes&apos;..
        /// </summary>
        internal static string If_so__and_if_iTunes_is_running_quit_iTunes {
            get {
                return ResourceManager.GetString("If_so__and_if_iTunes_is_running_quit_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you say YES, this project will be added to the existing batchfile. If you say NO, you&apos;ll be prompted for a different file name..
        /// </summary>
        internal static string If_you_say_YES__this_project_will_be_added_to_the_existing_batchfile {
            get {
                return ResourceManager.GetString("If_you_say_YES__this_project_will_be_added_to_the_existing_batchfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you say &apos;Yes&apos; you&apos;ll never be prompted to resume this project again..
        /// </summary>
        internal static string If_you_say_Yes_you_ll_never_be_prompted_to_resume_this_project_again {
            get {
                return ResourceManager.GetString("If_you_say_Yes_you_ll_never_be_prompted_to_resume_this_project_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish MarkAble to set this rate, please close down iTunes..
        /// </summary>
        internal static string If_you_wish_MarkAble_to_set_this_rate__please_close_down_iTunes {
            get {
                return ResourceManager.GetString("If_you_wish_MarkAble_to_set_this_rate__please_close_down_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like us to restore your previous settings, please close iTunes..
        /// </summary>
        internal static string If_you_would_like_us_to_restore_your_previous_settings__please_close_iTunes {
            get {
                return ResourceManager.GetString("If_you_would_like_us_to_restore_your_previous_settings__please_close_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore this?.
        /// </summary>
        internal static string Ignore_this_query {
            get {
                return ResourceManager.GetString("Ignore_this_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing audiobook into iTunes, please wait!.
        /// </summary>
        internal static string Importing_audiobook_into_iTunes__please_wait {
            get {
                return ResourceManager.GetString("Importing_audiobook_into_iTunes__please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid registration key!.
        /// </summary>
        internal static string Invalid_registration_key_exclaim {
            get {
                return ResourceManager.GetString("Invalid_registration_key_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid track duration, skipping track .
        /// </summary>
        internal static string Invalid_track_duration__skipping_track {
            get {
                return ResourceManager.GetString("Invalid_track_duration__skipping_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks as if you didn&apos;t finish processing CDs for &apos;&lt;booktitle&gt;&apos; by &lt;author&gt;..
        /// </summary>
        internal static string It_looks_as_if_you_didn_t_finish_processing_CDs_for_booktitle {
            get {
                return ResourceManager.GetString("It_looks_as_if_you_didn_t_finish_processing_CDs_for_booktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks as if you didn&apos;t finish processing files for &apos;&lt;booktitle&gt;&apos; by &lt;author&gt;.
        /// </summary>
        internal static string It_looks_as_if_you_didn_t_finish_processing_files_for_booktitle {
            get {
                return ResourceManager.GetString("It_looks_as_if_you_didn_t_finish_processing_files_for_booktitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes error.
        /// </summary>
        internal static string iTunes_error {
            get {
                return ResourceManager.GetString("iTunes_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes is not responding to MarkAble control.  Minimize MarkAble and check to see if iTunes is attempting to ask you a question..
        /// </summary>
        internal static string iTunes_is_not_responding_to_MarkAble_control {
            get {
                return ResourceManager.GetString("iTunes_is_not_responding_to_MarkAble_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes is still not responding to MarkAble control. Giving up..
        /// </summary>
        internal static string iTunes_is_still_not_responding {
            get {
                return ResourceManager.GetString("iTunes_is_still_not_responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes won&apos;t respond.
        /// </summary>
        internal static string iTunes_won_t_respond {
            get {
                return ResourceManager.GetString("iTunes_won_t_respond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkAble batch processing complete!.
        /// </summary>
        internal static string MarkAble_batch_processing_complete {
            get {
                return ResourceManager.GetString("MarkAble_batch_processing_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkAble has been updated and you will require a new registration key..
        /// </summary>
        internal static string MarkAble_has_been_updated_and_you_will_require_a_new_registration_key {
            get {
                return ResourceManager.GetString("MarkAble_has_been_updated_and_you_will_require_a_new_registration_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap markable_spash {
            get {
                object obj = ResourceManager.GetObject("markable_spash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing files.
        /// </summary>
        internal static string Missing_files {
            get {
                return ResourceManager.GetString("Missing_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3 files can&apos;t have chapter stops, sorry, but you can set an image which iTunes will use as cover artwork..
        /// </summary>
        internal static string MP3_files_can_t_have_chapter_stops {
            get {
                return ResourceManager.GetString("MP3_files_can_t_have_chapter_stops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MP3_small {
            get {
                object obj = ResourceManager.GetObject("MP3_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap neat_book_square {
            get {
                object obj = ResourceManager.GetObject("neat_book_square", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CD tracks could be read. Please check CD drive and whether iTunes is asking you a question..
        /// </summary>
        internal static string No_CD_tracks_could_be_read {
            get {
                return ResourceManager.GetString("No_CD_tracks_could_be_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lists found.
        /// </summary>
        internal static string No_lists_found {
            get {
                return ResourceManager.GetString("No_lists_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks.
        /// </summary>
        internal static string No_tracks {
            get {
                return ResourceManager.GetString("No_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready.
        /// </summary>
        internal static string Not_ready {
            get {
                return ResourceManager.GetString("Not_ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do!.
        /// </summary>
        internal static string Nothing_to_do_exclaim {
            get {
                return ResourceManager.GetString("Nothing_to_do_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nd.
        /// </summary>
        internal static string Ordinal_nd {
            get {
                return ResourceManager.GetString("Ordinal_nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd.
        /// </summary>
        internal static string Ordinal_rd {
            get {
                return ResourceManager.GetString("Ordinal_rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string Ordinal_st {
            get {
                return ResourceManager.GetString("Ordinal_st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        internal static string Ordinal_th {
            get {
                return ResourceManager.GetString("Ordinal_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otherwise, click &apos;No&apos; now..
        /// </summary>
        internal static string Otherwise__click__No__now {
            get {
                return ResourceManager.GetString("Otherwise__click__No__now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put Disc &lt;discnum&gt; of the set into your CD drive.  Wait until you can see iTunes list all the tracks, then click on OK..
        /// </summary>
        internal static string Please_put_Disc__discnum__of_the_set_into_your_CD_drive {
            get {
                return ResourceManager.GetString("Please_put_Disc__discnum__of_the_set_into_your_CD_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the author&apos;s name in Step 4.
        /// </summary>
        internal static string Please_set_the_author_s_name_in_Step_4 {
            get {
                return ResourceManager.GetString("Please_set_the_author_s_name_in_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the book&apos;s title in Step 3.
        /// </summary>
        internal static string Please_set_the_book_s_title_in_Step_3 {
            get {
                return ResourceManager.GetString("Please_set_the_book_s_title_in_Step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the CD drive in Step 1.
        /// </summary>
        internal static string Please_set_the_CD_drive_in_Step_1 {
            get {
                return ResourceManager.GetString("Please_set_the_CD_drive_in_Step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the creator&apos;s name in Step 4.
        /// </summary>
        internal static string Please_set_the_creator_s_name_in_Step_4 {
            get {
                return ResourceManager.GetString("Please_set_the_creator_s_name_in_Step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit &lt;webpage&gt; for more information..
        /// </summary>
        internal static string Please_visit_webpage_for_more_information {
            get {
                return ResourceManager.GetString("Please_visit_webpage_for_more_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, opening iTunes....
        /// </summary>
        internal static string Please_wait__opening_iTunes {
            get {
                return ResourceManager.GetString("Please_wait__opening_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems.
        /// </summary>
        internal static string Problems {
            get {
                return ResourceManager.GetString("Problems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process just the unprotected files?.
        /// </summary>
        internal static string Process_just_the_unprotected_files_query {
            get {
                return ResourceManager.GetString("Process_just_the_unprotected_files_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;&lt;booktitle&gt;&apos; by &lt;author&gt;.
        /// </summary>
        internal static string Processing_booktitle_by_author {
            get {
                return ResourceManager.GetString("Processing_booktitle_by_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file &apos;&lt;path&gt;&apos;.
        /// </summary>
        internal static string Processing_file_path {
            get {
                return ResourceManager.GetString("Processing_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing track &apos;&lt;trackname&gt;&apos;.
        /// </summary>
        internal static string Processing_track_trackname {
            get {
                return ResourceManager.GetString("Processing_track_trackname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing tracks....
        /// </summary>
        internal static string Processing_tracks {
            get {
                return ResourceManager.GetString("Processing_tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project was added to the batch file.
        /// </summary>
        internal static string Project_added_to_batch {
            get {
                return ResourceManager.GetString("Project_added_to_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected files encountered.
        /// </summary>
        internal static string Protected_files_encountered {
            get {
                return ResourceManager.GetString("Protected_files_encountered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_icon {
            get {
                object obj = ResourceManager.GetObject("question_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered to.
        /// </summary>
        internal static string Registered_to {
            get {
                return ResourceManager.GetString("Registered_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the project from the batch?.
        /// </summary>
        internal static string Remove_the_project_from_the_batch_query {
            get {
                return ResourceManager.GetString("Remove_the_project_from_the_batch_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Preferences.
        /// </summary>
        internal static string Restore_Preferences {
            get {
                return ResourceManager.GetString("Restore_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume?.
        /// </summary>
        internal static string Resume_query {
            get {
                return ResourceManager.GetString("Resume_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripping &quot;&lt;booktitle&gt;&quot; by &lt;author&gt;.
        /// </summary>
        internal static string Ripping_booktitle_by_author {
            get {
                return ResourceManager.GetString("Ripping_booktitle_by_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saying &apos;No&apos; will abandon the resume.
        /// </summary>
        internal static string Saying_No_will_abandon_the_resume {
            get {
                return ResourceManager.GetString("Saying_No_will_abandon_the_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip conversion?.
        /// </summary>
        internal static string Skip_conversion_query {
            get {
                return ResourceManager.GetString("Skip_conversion_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the files you have selected are protected by Digital Rights Management (DRM)..
        /// </summary>
        internal static string Some_of_the_files_you_have_selected_are_protected_by_Digital_Rights_Management {
            get {
                return ResourceManager.GetString("Some_of_the_files_you_have_selected_are_protected_by_Digital_Rights_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some problems were encountered during merging: .
        /// </summary>
        internal static string Some_problems_were_encountered_during_merging {
            get {
                return ResourceManager.GetString("Some_problems_were_encountered_during_merging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!.
        /// </summary>
        internal static string Sorry_exclaim {
            get {
                return ResourceManager.GetString("Sorry_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string Success_exclaim {
            get {
                return ResourceManager.GetString("Success_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure?.
        /// </summary>
        internal static string Sure_query {
            get {
                return ResourceManager.GetString("Sure_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering!.
        /// </summary>
        internal static string Thanks_for_registering {
            get {
                return ResourceManager.GetString("Thanks_for_registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch file is now empty.  Delete it?.
        /// </summary>
        internal static string The_batch_file_is_now_empty_Delete_it_query {
            get {
                return ResourceManager.GetString("The_batch_file_is_now_empty_Delete_it_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This batchfile already contains the following projects.
        /// </summary>
        internal static string This_batchfile_already_contains_the_following_projects {
            get {
                return ResourceManager.GetString("This_batchfile_already_contains_the_following_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try adding files in smaller groups, or use &apos;Select Folder&apos;.
        /// </summary>
        internal static string Try_adding_files_in_smaller_groups_or_use_Select_Folder {
            get {
                return ResourceManager.GetString("Try_adding_files_in_smaller_groups_or_use_Select_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again?.
        /// </summary>
        internal static string Try_again_query {
            get {
                return ResourceManager.GetString("Try_again_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to alter batch file!.
        /// </summary>
        internal static string Unable_to_alter_batch_file {
            get {
                return ResourceManager.GetString("Unable_to_alter_batch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create folder.
        /// </summary>
        internal static string Unable_to_create_folder {
            get {
                return ResourceManager.GetString("Unable_to_create_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create folder &lt;path&gt;.
        /// </summary>
        internal static string Unable_to_create_folder_path {
            get {
                return ResourceManager.GetString("Unable_to_create_folder_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create local app data folder.
        /// </summary>
        internal static string Unable_to_create_local_app_data_folder {
            get {
                return ResourceManager.GetString("Unable_to_create_local_app_data_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete batch file!.
        /// </summary>
        internal static string Unable_to_delete_batch_file {
            get {
                return ResourceManager.GetString("Unable_to_delete_batch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete existing file &lt;path&gt;.
        /// </summary>
        internal static string Unable_to_delete_existing_file_path {
            get {
                return ResourceManager.GetString("Unable_to_delete_existing_file_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete prior copy &lt;path&gt;.
        /// </summary>
        internal static string Unable_to_delete_prior_copy_path {
            get {
                return ResourceManager.GetString("Unable_to_delete_prior_copy_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine file size and duration..
        /// </summary>
        internal static string Unable_to_determine_file_size_and_duration {
            get {
                return ResourceManager.GetString("Unable_to_determine_file_size_and_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load image!.
        /// </summary>
        internal static string Unable_to_load_image_exclaim {
            get {
                return ResourceManager.GetString("Unable_to_load_image_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load initial file!.
        /// </summary>
        internal static string Unable_to_load_initial_file {
            get {
                return ResourceManager.GetString("Unable_to_load_initial_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to move converted file to &lt;path&gt;.
        /// </summary>
        internal static string Unable_to_move_converted_file_to_path {
            get {
                return ResourceManager.GetString("Unable_to_move_converted_file_to_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open batch file.
        /// </summary>
        internal static string Unable_to_open_batch_file {
            get {
                return ResourceManager.GetString("Unable_to_open_batch_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open iTunes!.
        /// </summary>
        internal static string Unable_to_open_iTunes {
            get {
                return ResourceManager.GetString("Unable_to_open_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open &lt;path&gt; for writing!.
        /// </summary>
        internal static string Unable_to_open_path_for_writing {
            get {
                return ResourceManager.GetString("Unable_to_open_path_for_writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save batch.
        /// </summary>
        internal static string Unable_to_save_batch {
            get {
                return ResourceManager.GetString("Unable_to_save_batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set cover artwork and bookmarking in iTunes. You may need to set this manually..
        /// </summary>
        internal static string Unable_to_set_cover_artwork_and_bookmarking_in_iTunes {
            get {
                return ResourceManager.GetString("Unable_to_set_cover_artwork_and_bookmarking_in_iTunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately ITunes (and therefore MarkAble) cannot process DRM protected files..
        /// </summary>
        internal static string Unfortunately_ITunes_cannot_process_DRM_protected_files {
            get {
                return ResourceManager.GetString("Unfortunately_ITunes_cannot_process_DRM_protected_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregistered.
        /// </summary>
        internal static string Unregistered {
            get {
                return ResourceManager.GetString("Unregistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning_exclaim {
            get {
                return ResourceManager.GetString("Warning_exclaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll now start to convert (&apos;rip&apos;) the tracks from each disc to an &lt;encodertype&gt; format.  Each disc should take about 2 to 5 minutes to process..
        /// </summary>
        internal static string We_ll_now_start_to_convert_the_tracks_from_each_disc_to_an__encodertype__format {
            get {
                return ResourceManager.GetString("We_ll_now_start_to_convert_the_tracks_from_each_disc_to_an__encodertype__format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re now converting all the audio files into &lt;fileformat&gt; format.  This can take quite a long while!.
        /// </summary>
        internal static string We_re_now_converting_all_the_audio_files_into_fileformat_format {
            get {
                return ResourceManager.GetString("We_re_now_converting_all_the_audio_files_into_fileformat_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it has completely shut down, click &apos;Yes&apos;..
        /// </summary>
        internal static string When_it_has_completely_shut_down__click__Yes {
            get {
                return ResourceManager.GetString("When_it_has_completely_shut_down__click__Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it has fully closed down, then click &apos;Yes&apos; below..
        /// </summary>
        internal static string When_it_has_fully_closed_down__then_click__Yes__below {
            get {
                return ResourceManager.GetString("When_it_has_fully_closed_down__then_click__Yes__below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to have entered a registration key for an earlier version of MarkAble..
        /// </summary>
        internal static string You_appear_to_have_entered_a_registration_key_for_an_earlier_version_of_MarkAble {
            get {
                return ResourceManager.GetString("You_appear_to_have_entered_a_registration_key_for_an_earlier_version_of_MarkAble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have selected too many files at once..
        /// </summary>
        internal static string You_may_have_selected_too_many_files_at_once {
            get {
                return ResourceManager.GetString("You_may_have_selected_too_many_files_at_once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t be asked again..
        /// </summary>
        internal static string You_won_t_be_asked_again {
            get {
                return ResourceManager.GetString("You_won_t_be_asked_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current preferences are for &lt;encodertype&gt; encoding..
        /// </summary>
        internal static string Your_current_preferences_are_for_encodertype_encoding {
            get {
                return ResourceManager.GetString("Your_current_preferences_are_for_encodertype_encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your iTunes encoder preferences have been changed by MarkAble..
        /// </summary>
        internal static string Your_iTunes_encoder_preferences_have_been_changed_by_MarkAble {
            get {
                return ResourceManager.GetString("Your_iTunes_encoder_preferences_have_been_changed_by_MarkAble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferred encoding rate has not been set in iTunes..
        /// </summary>
        internal static string Your_preferred_encoding_rate_has_not_been_set_in_iTunes {
            get {
                return ResourceManager.GetString("Your_preferred_encoding_rate_has_not_been_set_in_iTunes", resourceCulture);
            }
        }
    }
}
